title: 王凯
description: 做难且正确的事
tagline: 后端工程师
url: https://ai-withu.cn
avatar: /my.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - vendor/

# Optimize Jekyl SEO Tag
twitter:
  card: summary
logo: /my.jpg
social:
  name: 王凯
  links:
    - https://github.com/tjubigben
    - https://ai-withu.cn
lang: zh-CN

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: 王凯
  url: https://ai-withu.cn/about/
  email: 2605121231@qq.com
